NEI<-readRDS("summarySCC_PM25.rds")
SCC<-readRDS("Source_Classification_Code.rds")
sub1<-subset(NEI,NEI$fips=="24510")
str(sub1)
y<-tapply(sub1$Emissions,sub1$year,sum)
x<-c(1999,2002,2005,2008)
plot(x,y,ylab='Total PM2.5 Emission(Baltimore City, Maryland)',xlab='Year',type="l")
dev.copy(png,file="plot2.png")
dev.off()
