NEI<-readRDS("summarySCC_PM25.rds")
SCC<-readRDS("Source_Classification_Code.rds")
str(NEI)
table(NEI$year)
table(NEI$Pollutant)
table(NEI$type)
y<-tapply(NEI$Emissions,NEI$year,sum)
x<-unique(NEI$year)
plot(x,y,ylab='Total PM2.5 Emission',xlab='Year',type="l")
dev.copy(png,file="plot1.png")
dev.off()
